NAME=phonebook
FLAGS=-Wall -Wextra -Werror -std=c++98 -o
CC=c++
SRC=Contact.cpp\
	Contact.hpp\
	PhoneBook.cpp\
	PhoneBook.hpp\
	phonebook.cpp

all: $(NAME)

$(NAME): $(SRC)
		$(CC) $(SRC) $(FLAGS) $(NAME)