NAME=megaphone
FLAGS=-Wall -Wextra -Werror -std=c++98 -o
CC=c++
SRC=megaphone.cpp

all: $(NAME)

re:
	$(CC) $(NAME).cpp $(FLAGS) $(NAME)

fclean:
	rm -rf $(NAME)

clean:
	rm -rf $(NAME)
	

$(NAME): $(NAME).cpp
		$(CC) $(NAME).cpp $(FLAGS) $(NAME)
